# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweather.proto\x12\x07weather\"5\n\x0eWeatherRequest\x12\x10\n\x08latitude\x18\x01 \x01(\t\x12\x11\n\tlongitude\x18\x02 \x01(\t\"\x97\x02\n\x16\x43urrentWeatherResponse\x12\n\n\x02\x64t\x18\x01 \x01(\x05\x12\x0f\n\x07sunrise\x18\x02 \x01(\x05\x12\x0e\n\x06sunset\x18\x03 \x01(\x05\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\x12\n\nfeels_like\x18\x05 \x01(\x02\x12\x10\n\x08pressure\x18\x06 \x01(\x05\x12\x10\n\x08humidity\x18\x07 \x01(\x05\x12\x11\n\tdew_point\x18\x08 \x01(\x02\x12\x10\n\x08uv_index\x18\t \x01(\x02\x12\x0e\n\x06\x63louds\x18\n \x01(\x05\x12\x12\n\nvisibility\x18\x0b \x01(\x05\x12\x12\n\nwind_speed\x18\x0c \x01(\x02\x12\x13\n\x0bwind_degree\x18\r \x01(\x05\x12\x11\n\twind_gust\x18\x0e \x01(\x02\x32\x61\n\x0eWeatherService\x12O\n\x11GetCurrentWeather\x12\x17.weather.WeatherRequest\x1a\x1f.weather.CurrentWeatherResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_WEATHERREQUEST']._serialized_start=26
  _globals['_WEATHERREQUEST']._serialized_end=79
  _globals['_CURRENTWEATHERRESPONSE']._serialized_start=82
  _globals['_CURRENTWEATHERRESPONSE']._serialized_end=361
  _globals['_WEATHERSERVICE']._serialized_start=363
  _globals['_WEATHERSERVICE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
